---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: fruits
    provider: fabric8
    version: 15-SNAPSHOT
    group: com.example
  name: my-database-secret
stringData:
  user: luke
  password: secret
